name: Linux Clang Test

on: [push]

env:
  BUILD_CONFIGURATION: Debug

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y clang-19



    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        clang++-19 -std=c++26 -Wall -I caesium_lib/caesium_lib -I Caesium -I Tests \
        Tests/main.cpp \
        Tests/test_parse.cpp \
        Caesium/core/toCPP.cpp \
        Caesium/helpers.cpp \
        Caesium/structured/structurizer.cpp \
        Caesium/grammar/parse.cpp \
        Caesium/core/transpile_statement.cpp \
        Caesium/expression_visitor/transpile_expression_visitor.cpp \
        Caesium/type_visitor/transpile_member_call_visitor.cpp \
        Caesium/type_visitor/type_of_function_like_call_with_args_visitor.cpp \
        Caesium/type_visitor/type_of_postfix_member_visitor.cpp \
        Caesium/type_visitor/name_of_type_visitor.cpp \
        Caesium/type_visitor/type_of_resolution_operator.cpp \
        Caesium/builtin_visitor/transpile_builtin_call_with_args_visitor.cpp \
        Caesium/typename_visitor/type_of_typename_visitor.cpp \
        Caesium/typename_visitor/type_template_of_typename_visitor.cpp \
        Caesium/typename_visitor/typename_for_template_visitor.cpp \
        Caesium/typename_visitor/realise_typename_visitor.cpp \
        -lstdc++ -lstdc++exp
    - name: Test
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: ./a.out "Tests/Transpilation Tests"
