name: MSBuild debug

on: [push]

env:
  SOLUTION_FILE_PATH: .
  BUILD_CONFIGURATION: Debug
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1

    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}

    - name: Build-App
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /t:Tests:Rebuild /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}
      
    - name: Test
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: D:\a\Caesium\Caesium\x64\Debug\tests.exe
