name: MSBuild debug

on: [push]

env:
  SOLUTION_FILE_PATH: .
  BUILD_CONFIGURATION: Debug
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}

    - name: List files in caesium_lib submodule
      run: dir D:\a\Caesium\Caesium\caesium_lib

    - name: Build-Core
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild Caesium/Caesium.vcxproj -t:rebuild -property:Configuration=Debug -property:IncludePath=D:\a\Caesium\Caesium\caesium_lib\caesium_lib -property:LanguageStandard=stdcpp23 -property:Platform=x64

    - name: Build-Tests
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild Tests/Tests.vcxproj -t:build -property:Configuration=Debug -property:IncludePath=D:\a\Caesium\Caesium\caesium_lib\caesium_lib -property:LanguageStandard=stdcpp23 -property:Platform=x64

    - name: List Transpilation Tests
      run: dir D:\a\Caesium\Caesium\Tests\Tests

    - name: List Transpilation Tests
      run: dir "D:\a\Caesium\Caesium\Tests\Transpilation Tests"

    - name: Test Base
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: D:\a\Caesium\Caesium\Tests\x64\Debug\tests.exe

    - name: Test
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: D:\a\Caesium\Caesium\Tests\x64\Debug\tests.exe "D:\a\Caesium\Caesium\Tests\Transpilation Tests"
